var Inventario = require("../models/inventario");
var mongoose = require("mongoose");
var configDB = require("../config/database");

mongoose.connect(configDB.url);
//crea productos en un arreglo
const inventarios = [
{
	mp : "ACEITE",
	cantidadTotal : 0,
	presentacion : 18000,
	valorUni : 0,
	valorG : 0,
	stock : 0,
	valorTotalG : 0,
	stockReal: 0,
  diferencia: 0,
  valorDif: 0,
	rango: 0,
	bodega : "principal",
	estado: "inactivo"
},
{
	mp : "AGUA",
	cantidadTotal : 0,
	presentacion : 1000,
	valorUni : 0,
	valorG : 0,
	stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
	bodega : "principal",
	estado: "inactivo"
},
{
  mp : "AJONJOLI",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ALMIDON DE YUCA",
  cantidadTotal : 0,
  presentacion : 12000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "AREQUIPE ARTESANAL",
  cantidadTotal : 0,
  presentacion : 6000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "AREQUIPE INDUSTRIAL",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "AZUCAR BLANCO",
  cantidadTotal : 0,
  presentacion : 50000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAJAS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAPACILLO #2",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAPACILLO #3",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAPACILLO #4",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAPACILLO #5",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CAPACILLO #6",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CHIPS DE CHOCOLATE",
  cantidadTotal : 0,
  presentacion : 12500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CINTA TRANSPARENTE 100 MTS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "CINTA TRANSPARENTE 200 MTS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "COCO DESHIDRATADO",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "COLMAIZ",
  cantidadTotal : 0,
  presentacion : 12000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "COLOR AMARILLO",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "DESMOLDANTE",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "DIVISIONES GRANDES",
  cantidadTotal : 0,
  presentacion : 50,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "DIVISIONES LARGAS",
  cantidadTotal : 0,
  presentacion : 60,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "DIVISIONES PEQUEÑAS",
  cantidadTotal : 0,
  presentacion : 50,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE BANANO",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE CHOCOLATE",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE COCO",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE AREQUIPE",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE FRESA",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE LIMON",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE MANTEQUILLA",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE NARANJA",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE QUESO",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "ESENCIA DE VAINILLA",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "FECULA DE MAIZ",
  cantidadTotal : 0,
  presentacion : 25000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "GLASSE DE FRESA",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "GLASSE DE KIWI",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "GRAGEAS",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "GUAYABA INDUSTRIAL",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "GUAYABA ARTESANAL",
  cantidadTotal : 0,
  presentacion : 6000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "HARINA DE TRIGO ARTESANAL",
  cantidadTotal : 0,
  presentacion : 50000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "HARINA DE TRIGO PARA PAN",
  cantidadTotal : 0,
  presentacion : 50000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "HARINA DE TRIGO PARA GALLETA/PONQUE",
  cantidadTotal : 0,
  presentacion : 50000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "HUEVOS",
  cantidadTotal : 0,
  presentacion : 30,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 22 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 26 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 28 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 30 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 32 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LAMINA TRANSPARENTE 34 CM",
  cantidadTotal : 0,
  presentacion : 1000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LECHE EN POLVO",
  cantidadTotal : 0,
  presentacion : 25000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "LEVADURA",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MARGARINA INDUSTRIAL",
  cantidadTotal : 0,
  presentacion : 15000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MARGARINA INDUSTRIAL EXCELENCIA",
  cantidadTotal : 0,
  presentacion : 15000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MARGARINA ARTESANAL",
  cantidadTotal : 0,
  presentacion : 15000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MARGARINA HOJALDRE",
  cantidadTotal : 0,
  presentacion : 15000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MARGARINA HOJALDRE VITINA",
  cantidadTotal : 0,
  presentacion : 15000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "MEJORADOR",
  cantidadTotal : 0,
  presentacion : 500,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "POLVO PARA HORNEAR",
  cantidadTotal : 0,
  presentacion : 25000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "PROPINATO DE CALCIO",
  cantidadTotal : 0,
  presentacion : 12000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "PROTEINA AISLADA DE SOYA",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "SAL",
  cantidadTotal : 0,
  presentacion : 50000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "SALVADO DE TRIGO",
  cantidadTotal : 0,
  presentacion : 450,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "STICKER GRANDE 62 X 30",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "STICKER PEQUEÑO 29 X 30",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "TINTURA DE CARAMELO",
  cantidadTotal : 0,
  presentacion : 20000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "FIBRA DE POLLO",
  cantidadTotal : 0,
  presentacion : 7000,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "VIDEO JET 55 MM X 600 MTS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "VIDEO JET 55 MM X 1200 MTS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "VIDEO JET 55 MM X 700 MTS",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "VIDEO JET 33 MM",
  cantidadTotal : 0,
  presentacion : 1,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
},
{
  mp : "VINAGRE",
  cantidadTotal : 0,
  presentacion : 3800,
  valorUni : 0,
  valorG : 0,
  stock : 0,
	valorTotalG : 0,
	stockReal: 0,
	diferencia: 0,
	valorDif: 0,
	rango: 0,
  bodega : "principal",
	estado: "inactivo"
}
];
//recorre el arreglo producto por producto
var done = 0;
//for(var i = 0; i < inventarios.length; i++){
for(var i = 0; i < inventarios.length; i++){
	//save each product of the array in the model and database
	var newInventario = new Inventario(inventarios[i])
	newInventario.save(function(err,result){
		done++;
		if(done === inventarios.length){
			exit();
		}
	});
}
// se hizo esta funcion para desconectar el servidor debido a que el servidor trabaja de manera
//asyncrona entonces causaria un error  y no dejaria guardar  los productos
function exit(){
	mongoose.disconnect();
}
